#!/usr/bin/env bash

set -xo pipefail

if [[ "$1" == "apply" ]]; then
    # Uses each linter's option to apply the changes if it is supported
    black clinvar_ingest test
    isort clinvar_ingest test
    ruff --fix clinvar_ingest test
    pylint --disable=C,R,W clinvar_ingest
else
    # Check-only mode
    had_error=0
    black --check clinvar_ingest test || had_error=1
    isort --check-only clinvar_ingest test || had_error=1
    ruff check clinvar_ingest test || had_error=1
    pylint --disable=C,R,W clinvar_ingest || had_error=1
    exit $had_error
fi
