main:
    params: [args]
    steps:
        - log_args:
            call: sys.log
            args:
                data: ${args}
        - copy:
            call: http.post
            args:
                url: https://clinvar-ingest-kyle-dev-qmojsrhb3q-uc.a.run.app/copy
                #url: '${sys.get_env("CLOUD_RUN_SERVICE")}/copy'
                body: '${args}'
                auth:
                    type: OIDC
            result: copy_result
        - log_copy_result:
            call: sys.log
            args:
                data: ${copy_result}
        - parse:
            try:
                call: http.post
                args:
                    url: https://clinvar-ingest-kyle-dev-qmojsrhb3q-uc.a.run.app/parse
                    #url: '${sys.get_env("CLOUD_RUN_SERVICE")}/parse'
                    # body: '${copy_result.body}'
                    body:
                        input_path: '${copy_result.body.gcs_path}'
                        output_path: 'gs://clinvar-ingest/wf-outputs'
                    auth:
                        type: OIDC
                result: parse_result
            except:
                as: e
                steps:
                    - unhandled_exception:
                        raise: ${e}
        - log_parse_result:
            call: sys.log
            args:
                data: ${parse_result}
        - create_external_tables:
            call: http.post
            args:
                url: https://clinvar-ingest-kyle-dev-qmojsrhb3q-uc.a.run.app/create_external_tables
                #url: '${sys.get_env("CLOUD_RUN_SERVICE")}/create_external_tables'
                body:
                    destination_project: clingen-dev
                    destination_dataset: clinvar_ingest_new_wf_kyle_dev
                    source_table_paths: '${parse_result.body.parsed_files}'
                auth:
                    type: OIDC
            result: create_external_tables_result
        - result:
            return: ${create_external_tables_result}
