main:
    params: [args]
    steps:
        - copy:
            call: http.post
            args:
                url: '${sys.get_env("CLOUD_RUN_SERVICE")}/copy'
                body: '${args}'
                auth:
                    type: OIDC
            result: copy_result
        - parse:
            call: http.post
            args:
                url: '${sys.get_env("CLOUD_RUN_SERVICE")}/parse'
                body:
                    input_path: '${copy_result.body.gcs_path}'
                auth:
                    type: OIDC
            result: parse_result
        - create_external_tables:
            call: http.post
            args:
                url: '${sys.get_env("CLOUD_RUN_SERVICE")}/create_external_tables'
                body:
                    source_table_paths: '${parse_result.body.parsed_files}'
                auth:
                    type: OIDC
            result: create_external_tables_result
        - result:
            return: ${create_external_tables_result}
