main:
    params: [args]
    steps:
        - init:
            assign:
                - ingest_steps:
                    copy: ["ftp_path", "gcs_path"]
                    parse: ["parsed_files"]
                    create_external_tables: ["root"]
                - base_url: '${sys.get_env("CLOUD_RUN_SERVICE_URL") + "/"}'
                - initialize_step_url: '${base_url + "initialize_step"}'
                - step_status_url: '${base_url + "step_status"}'
                - workflow_execution_step_url: '${base_url + "create_workflow_execution_id/"}'
                - clinvar_file: '${args.Name}'
        - create_workflow_execution:
            call: http.post
            args:
                url: '${workflow_execution_step_url + clinvar_file}'
                body:
                auth:
                    type: OIDC
            result: workflow_execution_step_result
        - for_in_steps:
            for:
                value: step
                in: ${keys(ingest_steps)}
                steps:
                    - log_step_key:
                        call: sys.log
                        args:
                            data: '${"Step is: " + step}'
                    - init_variables:
                        assign:
                            - step_name: '${text.to_upper(step)}'
                            - result_copy_vars: ingest_steps[step]
                    - log_execute_args:
                        call: sys.log
                        args:
                            data: '${"executing: " + step_name + " " + base_url + step + " " + clinvar_file}'
                    - initialize_step:
                        call: http.post
                        args:
                            url: '${initialize_step_url}'
                            body:
                                step_name: '${step_name}'
                                workflow_execution_id: '${clinvar_file}'
                            auth:
                                type: OIDC
                        result: initialize_step_result
                    - log_initialize_step_result:
                        call: sys.log
                        args:
                            data: '${initialize_step_result}'
                    - call_step:
                        call: http.post
                        args:
                            url: '${base_url + step}'
                            body: '${args}'
                            auth:
                                type: OIDC
                        result: call_step_result
                    - log_call_step_result:
                        call: sys.log
                        args:
                            data: '${call_step_result}'
                    - status_check:
                        call: http.post
                        args:
                            url: '${step_status_url}'
                            body:
                                step_name: '${step_name}'
                                workflow_execution_id: '${clinvar_file}'
                            auth:
                                type: OIDC
                        result: status_check_result
                    - log_status_check_result:
                        call: sys.log
                        args:
                            data: '${status_check_result}'
                    - check_if_complete:
                        switch:
                            - condition: ${"FAILED" == status_check_result}
                              next: step_failed
                            - condition: ${"SUCCEEDED" == status_check_result}
                              next: step_succeeded
                    - wait_for_result:
                        call: sys.sleep
                        args:
                            seconds: 120
                        next: status_check
                    - step_succeeded:
                        steps:
                            - update_args_with_step_results:
                                for:
                                    value: var
                                    in: ${result_copy_vars}
                                    steps:
                                        - assign_vars:
                                            assign:
                                                - args[var]: ${status_check_result[var]}
                            - return_args:
                                return: args
                    - step_failed:
                        raise: '${"Step " + step_name + " failed for " + clinvar_file + " " + status_check_result.failure}'
