name: CI
on:
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Use pip cache
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
            restore-keys: |
              ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install '.[dev]'
      - name: Black formatting
        run: black --check clinvar_ingest test
      - name: Sort imports
        run: isort --check-only --profile black clinvar_ingest test
      - name: Ruff lint
        run: ruff check clinvar_ingest test
      # Pylint catches some things that Ruff doesn't yet support
      # Run error-only mode `--disable=C,R,W` == `-E`
      - name: Pylint
        run: pylint --disable=C,R,W clinvar_ingest
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Use pip cache
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
            restore-keys: |
              ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install '.[dev]'
      - name: Run tests
        run: pytest -v
