name: CI
on:
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # I think setup-python v4 has a builtin cache that might be easier to use!
      # I'd also suggest just using the most recent version of python (3.12?) since 
      # this is greenfield and internal.
      # we'd also get the StrEnum class in 3.11 which is bomb.
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Use pip cache
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
            restore-keys: |
              ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install '.[dev]'
      - name: Black formatting
        run: black --check clinvar_ingest test
      - name: Sort imports
        run: isort --check-only clinvar_ingest test
      # Out of curiousity, what we seeing pylint catch that ruff doesn't?
      # We might consider turing on every possible ruff option just to see what happens,
      # especially since this is greenfield repo.
      - name: Ruff lint
        run: ruff check clinvar_ingest test
      # Pylint catches some things that Ruff doesn't yet support
      # Run error-only mode `--disable=C,R,W` == `-E`
      - name: Pylint
        run: pylint --disable=C,R,W clinvar_ingest
      # We should try to get mypy/pyright working here since this is a greenfield project.
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Use pip cache
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
            restore-keys: |
              ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install '.[dev]'
      - name: Run tests
        run: pytest -v
