name: Deploy Job
run-name: Deploy ${{ github.event.workflow_run.head_branch }} by @${{ github.actor }}

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - issue-104-job-auto-deploy

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: authenticate to google cloud
        id: "auth"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/522856288592/locations/global/workloadIdentityPools/clingen-actions-pool/providers/clingen-github-actions
          service_account: clinvar-ingest-deployment@clingen-dev.iam.gserviceaccount.com

      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: set env vars
        run: |
          export branch=${{ github.event.workflow_run.head_branch }}
          export commit=${{ github.event.workflow_run.head_commit }}
          echo "branch=$branch" >> $GITHUB_ENV
          echo "commit=$commit" >> $GITHUB_ENV
          echo "instance_name=clinvar-ingest-$branch" >> $GITHUB_ENV

      - name: build and deploy
        run: |
          bash misc/bin/deploy-job.sh

      - name: run test pipeline
        run: |
          export JOB_WAIT=1
          echo "JOB_WAIT=$JOB_WAIT" >> $GITHUB_ENV
          bash misc/bin/execute-job.sh

  comment_pr:
    runs-on: ubuntu-latest
    # If the workflow run was triggered by a pull request, comment on the PR with the results
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    needs: release
    steps:
      - name: add comment to pr
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed ${{ github.event.workflow_run.head_branch }} to clinvar-ingest-${{ github.event.workflow_run.head_branch }}'
            })
