name: Release
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - 77-parameterize-workflow-action

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: authenticate to google cloud
        id: "auth"
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/522856288592/locations/global/workloadIdentityPools/clingen-actions-pool/providers/clingen-github-actions
          service_account: clinvar-ingest-deployment@clingen-dev.iam.gserviceaccount.com

      - name: "setup gcloud sdk"
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push image
        run: |-
          gcloud builds submit --quiet --substitutions="COMMIT_SHA=${{ github.event.workflow_run.head_sha }}" --config .cloudbuild/docker.cloudbuild.yaml --gcs-log-dir=gs://clinvar-ingest/build/logs .

      - name: Change image on cloud run service
        run: |-
          gcloud run deploy clinvar-ingest --region us-central1 --image gcr.io/clingen-dev/clinvar-ingest:latest

      - name: Get cloud run service url
        run: |-
          CLOUD_RUN_SERVICE=$(gcloud run services describe clinvar-ingest --region us-central1 --format='value(status.url)')
          echo "CLOUD_RUN_SERVICE=${CLOUD_RUN_SERVICE}" >> $GITHUB_ENV

      - name: Deploy Workflow
        # https://cloud.google.com/workflows/docs/use-environment-variables#gcloud
        run: |-
          set -u
          gcloud workflows deploy clinvar-ingest \
            --set-env-vars=CLOUD_RUN_SERVICE=${CLOUD_RUN_SERVICE},PARSE_OUTPUT_PREFIX=gs://clinvar-ingest/main-release-outputs,BQ_DEST_PROJECT=clingen-dev,BQ_DEST_DATASET=clinvar_ingest_main_deploy  \
            --source=workflow.yaml
